# site settings

title: Erwann Messoah
description: Game Design Student
taglong: Game Design and Game Programming
tagshort: Tiwann
url: https://tiwann.com
baseurl: ""
permalink: pretty
repo: https://github.com/tiwann/tiwann.github.io

# author settings

author:
  name: Erwann Messoah
  email: erwann.messoah@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: tiwann
  instagram: prodtiwann
  linkedin: tiwann
  artstation: tiwann

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
